//动画BG
var  animation={
				bg:[
					"./animation/img1/bg/bg1.png",
					"./animation/img1/bg/bg2.png",
					"./animation/img1/bg/bg3.png",
					"./animation/img1/bg/bg4.png",
					"./animation/img1/bg/bg5.png"	
				],
				time:[
					"./animation/img1/time/Time3.png",
					"./animation/img1/time/Time2.png",
					"./animation/img1/time/Time1.png"
				],
				earth:[
					"./animation/img1/earth/earth.png"
				],
				fragment:[
					"./animation/img1/fragment/Fragment1.png",
					"./animation/img1/fragment/Fragment2.png",
					"./animation/img1/fragment/Fragment3.png",
					"./animation/img1/fragment/Fragment4.png"
				],
				title:[
					"./animation/img1/title/bgnuber.png",
					"./animation/img1/title/bgText.png",
					["前端生涯"],
					"./animation/img1/title/LightSpot.png"
				],
				title1:[
					"./animation/img1/title/titleBg1.png",
					"./animation/img1/title/titleBg2.png"
				],
				img2:[
					"./animation/img2/bg1.png",
					"./animation/img2/bg2.png",
					"./animation/img2/bg3.png",
					"./animation/img2/earth.png"
				],
				img2Text:[
					["我的技能"],
					["•掌握技能：HTML5、CSS、CSS3、JS、ajax。"],
					["•掌握库与框架: jQery、Vue、less、iScroll、TwennMax。"],
					["•PC端：最低兼容IE6，以及各大主流浏览器。"],
					["•布局：响应式布局、瀑布流、圣杯布局以及自定义布局。"],
					["•移动端：兼容Android、IOS系统；兼容移动端浏览器：QQ、微信、Firefox、chrome、UC、猎豹等"],
					["•爱研究、追求完美、并且优化产品，尽量减少资源的消耗。"],
				],
				img3:[
					"./animation/img3/bg1.png",
					"./animation/img3/bg2.png",
					"./animation/img3/bg3.png",
					"./animation/img3/earth.png",
					"./animation/img3/bg4.png",
					"./animation/img3/border.png",
					["个人信息"],
					"./animation/img3/bottom.png",
					["一个问题百思解、一个创新夜难眠。"]
				],
				name:[
					"./animation/img3/border.png",
					"./animation/img3/img.jpg",
					["滕德勇"],
				],
				img4:[
					"./animation/img4/bg1.png",
					"./animation/img4/bg2.png",
					"./animation/img4/bg3.png",
					"./animation/img4/earth.png",
					"./animation/img3/bottom.png",
					["时光之轴"],
					"./animation/img4/Bar1.png",
					"./animation/img4/Bar2.png"
				],
				img4Light:[
					"./animation/img4/LightSpot.png"
				],
				img4TopText:[
					["2016 &nbsp; July"],
					["2016 &nbsp; July"],
					["2016 &nbsp; August"],
					["2016 &nbsp; August"],
					["2016 &nbsp; November"]
				],
				img4BottomText:[
					["携程的首页兼容IE6的页面"],
					["uehtml页面响应式编写完毕"],
					["3D立体空间家具房"],
					["3D酷炫双模式时钟"],
					["移动端酷炫VR安踏"]
				],
				img5:[
					"./animation/img5/bg1.png",
					"./animation/img5/bg2.png",
					"./animation/img5/bg3.png",
					"./animation/img5/bg4.png",
					"./animation/img5/border.png",
					"./animation/img5/bg5.png",
					"./animation/img5/bg6.png",
					["我的作品"],
					"./animation/img5/bottom.png",
					["欢迎你来欣赏"],
					"./animation/img5/LightSpot.png",
					["查看更多作品"]
				],
				worksS:[
					"./animation/works/tab.gif",
				]
			   }
var audioM=["./audio/zhaowuzhe.mp3"]
